### ISSUE TITLE
Solve the bug to start sending data by the device

### ISSUE THREAD

**Issue by svaleroc** [Code-and-Response/Prometeo#85]
There is a known issue with how the device sends data. We need to know how to reproduce, so that we can make the change. We might also ask the Project OWL folks if it's an issue they ran into.

**Comment by krook** [comment]
Simulator vs device issue. @derekteay to follow up with @joraco-dev

**Comment by joraco-dev** [comment]
Please, @svaleroc @mrodrise could you ellaborate on this? I don't remember what was going here or what was the issue.

Thanks

**Comment by mrodrise** [comment]
Hello, the problem here was that when you connect a device in order to send data to the IBM Cloud, doesn't appear the status of the firefighter in the dashboard.

There is a trick you can do, you can go to IOT platform simulation, simulate a device and then we'll appear both devices in the dashboard, the simulated and the real.

Regards,
Marco.

**Comment by krook** [comment]
Ah, so a test from the simulator is required before any real data is shown. Does this happen just once for new devices, or is it a process that has to be worked around regularly?

**Comment by mrodrise** [comment]
It happens regularly, I only test with one real device because I have only one. I think that if you have more than one device, there is not problem but I'm not sure. Maybe Josep can give more information.
